### ISSUE TITLE
Trouble Running for the First Time

### ISSUE THREAD

**Issue by Zackery** [0x263b/Stats#2]
Hello, I'm trying to setup Twitch logging. I configure the config.yaml file and I run `./stats_twitch.rb`. Once doing so, I get the error.

```
./stats.rb:278:in `initialize': No such file or directory @ rb_sysopen - /home/Stats/twitch/#timmac.log (Errno::ENOENT)
        from ./stats.rb:278:in `open'
        from ./stats.rb:278:in `<main>'
```

So, understandable, I create the folder and log file. Once done, I run the program again, which results in 
```
./stats_twitch.rb:348:in `at': can't convert nil into an exact number (TypeError)
        from ./stats_twitch.rb:348:in `<main>'
```
Troubleshooting, I discovered the database file isn't being created by the script, so I create a `database.json` file, and put `{}` in it's contents. Doing this results in

```
./stats_twitch.rb:282:in `block in <main>': undefined method `has_key?' for nil:NilClass (NoMethodError)
        from ./stats_twitch.rb:280:in `each'
        from ./stats_twitch.rb:280:in `<main>'
```

From here, I'm not sure what to do. Assistance would be appreciated, thank you!

**Comment by 0x263b** [comment]
Have you tried putting something in your log file? I just tested it with two lines in the log, and it worked fine. Try:

```
[2006-01-02 15:04:05 -0700] <joebloggs> This is a message
[2006-01-02 15:04:05 -0700] * joebloggs is preforming an action
```

then 

```
$ chmod u+x stats_twitch.rb
$ ./stats_twitch.rb
```

**Comment by Zackery** [comment]
Adding those contents to the log file, while the `database.json` file is created results in:

```
./stats_twitch.rb:282:in `block in <main>': undefined method `has_key?' for nil:                                                NilClass (NoMethodError)
        from ./stats_twitch.rb:280:in `each'
        from ./stats_twitch.rb:280:in `<main>'
```

Removing the database file, it gives me this error.

```
[2006-01-02 15:04:05 -0700] <joebloggs> This is a message
[2006-01-02 15:04:05 -0700] * joebloggs is preforming an action
./stats_twitch.rb:417:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

Sorry for the inconvenience, and thank you for the help.

**Comment by 0x263b** [comment]
Which ruby version are you using, and on what OS?

**Comment by 0x263b** [comment]
In your second error what is happening is the script will output the lines in the log that it had trouble with ([L187](https://github.com/0x263b/Stats/blob/master/stats_twitch.rb#L187)). In this case it's having trouble with each line. My best guess is it's an encoding issue with the log file, but I can't be sure. 

If you delete lines `94`, `186`, `187`, `188`, it will give you a more detailed description of what is going wrong.

**Comment by IllusionaryOne** [comment]
It was parsing the format of the logs from a different project that we work on.  I was able to modify the script to handle the different format and clean up some exception handling.

**Comment by afranco8** [comment]
I'm getting this error aswell. Any chance to help? I'm reading the example log but getting this:

./stats.rb
[2006-01-02 15:04:05 -0700] <joebloggs> This is a message
[2006-01-02 15:04:05 -0700] * joebloggs is preforming an action
./stats.rb:284:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

any help?
